### ISSUE TITLE
Latest version `1.5.0` no longer export `ImageKit` variable to global scope

### ISSUE THREAD

**Issue by Plausible0Bug** [imagekit-developer/imagekit-javascript#58]
Error I'm getting:
```
file_upload.js:3 Uncaught ReferenceError: ImageKit is not defined
    at HTMLDocument.<anonymous> (file_upload.js:3:19)
    at i (jquery.min.js:2:27151)
    at Object.fireWith [as resolveWith] (jquery.min.js:2:27914)
    at Function.ready (jquery.min.js:2:29707)
    at HTMLDocument.J (jquery.min.js:2:29892)
```
Tag used to import imagekit javascript client:
```
<script src="https://unpkg.com/imagekit-javascript@1.5.0/dist/imagekit.min.js"></script>
```

Maybe related?
https://github.com/imagekit-developer/imagekit-nodejs/issues/54

**Comment by imagekitio** [comment]
Please check version 1.5.1

**Comment by Plausible0Bug** [comment]
Thanks, I can confirm `1.5.1` is now working properly.
